### ISSUE TITLE
Support staging/non-default endpoint for ACME operations

### ISSUE THREAD

**Issue by eliasp** [nixcloud/nixcloud-webservices#41]
To prevent running into [rate-limits](https://letsencrypt.org/docs/rate-limits/) during tests/for debugging or to keep experimental certificates out of [CT logs to which LetsEncrypt publishes](https://letsencrypt.org/certificates/#certificate-transparency), it would be quite helpful to be able to use the [LetsEncrypt staging API](https://letsencrypt.org/docs/staging-environment/).

Furthermore, in case (hopefully) some other CAs start offering ACME or someone runs a company internal ACME CA (e.g. using [Boulder](https://github.com/letsencrypt/boulder)), a custom ACME API URL would have to be defined.

I'm not sure yet what to suggest in terms of the structure to use here:

Introduce an `ACME-staging` and an `ACME-custom` variant for `nixcloud.TLS.certs.<name>.mode` or rather introduce suboptions like `staging = true/false` and `apiUrl`?

`security.acme` already provides a `production = true/false` option which could be used for parts of this.

**Comment by qknight** [comment]
nixcloud.TLS builds on top of `security.acme` for the moment when using `mode = "ACME"` for a certificate. That also means you can set the global `production` variable like this:

```
security.acme.production = false;
```

For instance, from your `configuration.nix` or whatever module you linked from there. 

Does this help?

**Comment by eliasp** [comment]
It helps for the use-case of switching between LetsEncrypt production and staging, but we should keep in mind that LE is just a "default" ACME provider and a scenario where one runs his own internal ACME CA or another provider offers ACME at some point should be considered.

I don't think there's an explicit need to implement this right now, I just want to make sure it is considered in terms of how the options are structured and how `security.acme` is used within nixcloud-webservices (e.g. one might want to decide to have 3 domains, 2 on production, 1 on staging for tests or so).

**Comment by qknight** [comment]
Our long term goal is to:

* get rid of `security.acme` and implement their features in `nixcloud.TLS`
* get rid of `simp_le` and replace it by something more recent, aszlig has some ideas

BUT for now it is good enough since it is still working well and we don't have the resources to move on yet.

**Comment by eliasp** [comment]
> So your motivation would be to put this into the certs record, so the production flag can be set per certificate, right?

Correct!

**Comment by qknight** [comment]
at the moment `security.acme.production` is a global variable, see https://nixos.org/nixos/options.html#security.acme

we'd have to patch `security.acme` and since my last contact to the developers i'd rather integrate the missing 100 lines of code into `nixcloud.TLS` before touching `security.acme` again. this would have some benefits:

* only one abstraction to manage, `nixcloud.TLS` and not security.acme
* we don't have to wrap `security.acme` anymore which is complicated given the many different targets we have to catch and the problem that their configurations wont' merge compared to the `nixcloud.TLS` ones (which was the main point of writing nixcloud.TLS)
* we could get rid of `simp_le` and use the 'better' version of the client program.... whatever that is
